title: <h1> Kenny Dunn </h1> # your name (or website title) here
logo: "/images/KennyDblD.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h2> Data Driven Leader </h2> <br><br>
 <h4> Love Finding Business Insights Through Data Analysis </h4>  <br><br>
 <h4> Husband, Girl Dad, Poodle Dad, Foodie, Baseball Fanatic and Sport Lover </h4>  <br><br>
    <a href="https://www.linkedin.com/in/kennyddunn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
