title: Kenny Dunn # your name (or website title) here
logo: "/images/KennyDblD.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h4> Data Driven Leader </h4> <br><br> 
  Husband, Girl Dad, Poodle Dad, Foodie, Baseball Fanatic and Sport Lover  <br><br>
  Love Finding Business Insights Through Data Analysis  <br><br>
  <a href="https://www.linkedin.com/in/kennyddunn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
